### ISSUE TITLE
Add Access-Control-Allow-Origin to respnse header for cross domain requests

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd-cctray#1]
To test our build monitor I need to run it on my develop machine located in another domain. Because of this the monitor doesn't have the permission to request the cctray of the pipeline.
Please add

"Access-Control-Allow-Origin" "*" 

to the response header to enable cross domain monitoring. Because of security risks I would suggest a fourth optional parameter for the function cctray-handler-for. You can just make a simple signature switch to have a default value ("*") and let people restrict requests to their domain if they want it.

Regards,
Simon

**Comment by flosell** [comment]
I see that this is a valid use-case. 

However, to adhere to the common style of ring, I'd prefer not to add such a feature to the signature of `cctray-handler-for` and wrap the returned ring-handler instead. 
There's already a library out there that seems to do the job: https://github.com/r0man/ring-cors

Let me know if this works for you.
